### ISSUE TITLE
settings.py

### ISSUE THREAD

**Issue by rafaelribeiroo** [keshane/keshane.com#1]
Hey, how are u? Please, can u provide your settings.py configuration for emails?

**Comment by keshane** [comment]
I'd like to not share my whole settings.py file, but I can share the configuration for email. It's simply

`EMAIL_HOST_USER = "blog@keshane.com"`
`EMAIL_HOST_PASSWORD = "somesecurepassword"`
`EMAIL_USE_TLS = True`

Does this help you?
For what it's worth, my SMTP server is running on the same server as my Django application.

**Comment by rafaelribeiroo** [comment]
Can u pass me the value of DOMAIN? I just need of this now

**Comment by keshane** [comment]
DOMAIN is just "https://keshane.com." It was something I added to get the domain name when the code didn't have access to a request.
Are you trying to implement the unsubscribe link?

**Comment by rafaelribeiroo** [comment]
Yes, I'm trying to implement, your code is very good
